################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/tools \
src/playground \
src/partition/refinement \
src/partition \
src/partition/initial_partitioning \
src/partition/initial_partitioning/application \
src/partition/coarsening \
src/lib/serializer \
src/lib/io \
src/lib/datastructure \
src/external/binary_heap \
src/application \
release/src/tools/CMakeFiles/mtx_to_hgr_converter_test.dir \
release/src/tools/CMakeFiles/MtxToHgr.dir \
release/src/tools/CMakeFiles/HypergraphStats.dir \
release/src/tools/CMakeFiles/GraphToHgr.dir \
release/src/playground/CMakeFiles/pq_test.dir \
release/src/partition/refinement/CMakeFiles/two_way_fm_refiner_test.dir \
release/src/partition/refinement/CMakeFiles/max_gain_node_k_way_fm_refiner_test.dir \
release/src/partition/refinement/CMakeFiles/hyperedge_fm_refiner_test.dir \
release/src/partition/initial_partitioning/application/CMakeFiles/InitialPartitioningKaHyPar.dir \
release/src/partition/initial_partitioning/application/CMakeFiles/HypergraphBenchmarkTests.dir \
release/src/partition/initial_partitioning/CMakeFiles/initial_partitioner_base_test.dir \
release/src/partition/coarsening/CMakeFiles/rater_test.dir \
release/src/partition/coarsening/CMakeFiles/lazy_update_heavy_edge_coarsener_test.dir \
release/src/partition/coarsening/CMakeFiles/hyperedge_coarsener_test.dir \
release/src/partition/coarsening/CMakeFiles/heuristic_heavy_edge_coarsener_test.dir \
release/src/partition/coarsening/CMakeFiles/full_heavy_edge_coarsener_test.dir \
release/src/partition/CMakeFiles/partitioner_test.dir \
release/src/partition/CMakeFiles/metrics_test.dir \
release/src/lib/io/CMakeFiles/hypergraph_io_test.dir \
release/src/lib/datastructure/CMakeFiles/priority_queue_test.dir \
release/src/lib/datastructure/CMakeFiles/kway_priority_queue_test.dir \
release/src/lib/datastructure/CMakeFiles/hypergraph_test.dir \
release/src/application/CMakeFiles/KaHyPar.dir \
release/gmock-prefix/src/gmock-build/gtest/CMakeFiles/gtest_main.dir/src \
release/gmock-prefix/src/gmock-build/gtest/CMakeFiles/gtest.dir/src \
release/gmock-prefix/src/gmock-build/CMakeFiles/gmock_main.dir/src \
release/gmock-prefix/src/gmock-build/CMakeFiles/gmock_main.dir/gtest/src \
release/gmock-prefix/src/gmock-build/CMakeFiles/gmock.dir/src \
release/gmock-prefix/src/gmock-build/CMakeFiles/gmock.dir/gtest/src \
release/gmock-prefix/src/gmock-build/CMakeFiles/2.8.12.2/CompilerIdCXX \
release/gmock-prefix/src/gmock-build/CMakeFiles/2.8.12.2/CompilerIdC \
release/CMakeFiles/SQLPlotTools.dir/src/lib/serializer \
release/CMakeFiles/RandomFunctions.dir/src/tools \
release/CMakeFiles/Partitioner.dir/src/partition \
release/CMakeFiles/2.8.12.2/CompilerIdCXX \
gmock/test \
gmock/src \
gmock/gtest/xcode/Samples/FrameworkSample \
gmock/gtest/test \
gmock/gtest/src \
gmock/gtest/samples \
gmock/gtest/fused-src/gtest \
gmock/gtest/codegear \
gmock/fused-src \
debug/src/tools/CMakeFiles/mtx_to_hgr_converter_test.dir \
debug/src/tools/CMakeFiles/MtxToHgr.dir \
debug/src/tools/CMakeFiles/HypergraphStats.dir \
debug/src/tools/CMakeFiles/GraphToHgr.dir \
debug/src/playground/CMakeFiles/pq_test.dir \
debug/src/partition/refinement/CMakeFiles/two_way_fm_refiner_test.dir \
debug/src/partition/refinement/CMakeFiles/max_gain_node_k_way_fm_refiner_test.dir \
debug/src/partition/refinement/CMakeFiles/hyperedge_fm_refiner_test.dir \
debug/src/partition/initial_partitioning \
debug/src/partition/initial_partitioning/application/CMakeFiles/InitialPartitioningKaHyPar.dir \
debug/src/partition/initial_partitioning/application/CMakeFiles/HypergraphBenchmarkTests.dir \
debug/src/partition/initial_partitioning/CMakeFiles/initial_partitioner_base_test.dir \
debug/src/partition/coarsening/CMakeFiles/rater_test.dir \
debug/src/partition/coarsening/CMakeFiles/lazy_update_heavy_edge_coarsener_test.dir \
debug/src/partition/coarsening/CMakeFiles/hyperedge_coarsener_test.dir \
debug/src/partition/coarsening/CMakeFiles/heuristic_heavy_edge_coarsener_test.dir \
debug/src/partition/coarsening/CMakeFiles/full_heavy_edge_coarsener_test.dir \
debug/src/partition/CMakeFiles/partitioner_test.dir \
debug/src/partition/CMakeFiles/metrics_test.dir \
debug/src/lib/io/CMakeFiles/hypergraph_io_test.dir \
debug/src/lib/datastructure/CMakeFiles/priority_queue_test.dir \
debug/src/lib/datastructure/CMakeFiles/kway_priority_queue_test.dir \
debug/src/lib/datastructure/CMakeFiles/hypergraph_test.dir \
debug/src/application/CMakeFiles/KaHyPar.dir \
debug/gmock-prefix/src/gmock-build/gtest/CMakeFiles/gtest_main.dir/src \
debug/gmock-prefix/src/gmock-build/gtest/CMakeFiles/gtest.dir/src \
debug/gmock-prefix/src/gmock-build/CMakeFiles/gmock_main.dir/src \
debug/gmock-prefix/src/gmock-build/CMakeFiles/gmock_main.dir/gtest/src \
debug/gmock-prefix/src/gmock-build/CMakeFiles/gmock.dir/src \
debug/gmock-prefix/src/gmock-build/CMakeFiles/gmock.dir/gtest/src \
debug/gmock-prefix/src/gmock-build/CMakeFiles/2.8.12.2/CompilerIdCXX \
debug/gmock-prefix/src/gmock-build/CMakeFiles/2.8.12.2/CompilerIdC \
debug/CMakeFiles/SQLPlotTools.dir/src/lib/serializer \
debug/CMakeFiles/RandomFunctions.dir/src/tools \
debug/CMakeFiles/Partitioner.dir/src/partition \
debug/CMakeFiles/InitialPartitioner.dir/src/partition/initial_partitioning/application \
debug/CMakeFiles/2.8.12.2/CompilerIdCXX \
cmake/modules \

